export const TERMS_OF_SERVICE_TEXT = `# Terms of Service

**Last updated: August 11, 2026**

Welcome to AI Study Buddy ("we," "us," "our," or the "Service"), operated by Ayan Ahmed ("Company," "I," or "we"), based in Lahore, Pakistan. These Terms of Service ("Terms") govern your access to and use of our website, application, and related services.

By creating an account or using the Service, you agree to these Terms. If you do not agree, do not use the Service.

## 1. Eligibility

You must be at least 13 years old to use the Service. If you are under 18, you confirm that a parent or legal guardian has reviewed and agreed to these Terms on your behalf.

## 2. Your Account

- You are responsible for maintaining the confidentiality of your login credentials and for all activity under your account.
- You agree to provide accurate information when creating an account (including via Firebase Authentication or any third-party sign-in method we support).
- We may suspend or terminate accounts that violate these Terms.

## 3. Description of the Service

AI Study Buddy provides AI-assisted study tools, including but not limited to: notebook and note organization, AI-generated summaries and study guides, flashcards, quizzes, mind maps, resume building, scholarship and university tracking, and related features. Some features are powered by third-party AI models (including Google's Gemini API) and third-party infrastructure (including Firebase).

## 4. AI-Generated Content — Important Disclaimers

- Content generated by the Service (summaries, quizzes, study plans, feedback, chat responses, etc.) is produced by AI models and **may contain errors, inaccuracies, or outdated information**.
- AI-generated content is provided for study and informational purposes only and should not be treated as professional, academic, financial, or admissions advice.
- You are responsible for independently verifying any AI-generated content before relying on it academically or professionally (for example, before submitting AI-generated material as your own work — see Section 5).

## 5. Academic Integrity

You are solely responsible for complying with your school's or institution's academic integrity, plagiarism, and AI-usage policies. We do not guarantee that content generated through the Service is compliant with any specific institution's rules, and we are not responsible for any academic consequences resulting from your use of the Service.

## 6. User Content

- "User Content" means any notes, files, documents, images, or other material you upload or create using the Service.
- You retain ownership of your User Content. By uploading it, you grant us a limited license to store, process, and transmit it (including to third-party AI providers) solely to operate and improve the Service.
- You represent that you have the necessary rights to any content you upload and that it does not infringe third-party rights or violate applicable law.
- We may remove content that violates these Terms.

## 7. Subscriptions & Payments

- Certain features require a paid subscription ("Premium" / "Pro" tier).
- Prices, billing frequency, and included features are as described at the time of purchase.
- Subscriptions automatically renew at the end of each billing cycle unless cancelled before the renewal date.
- Payments are non-refundable except where required by applicable law.
- We reserve the right to change pricing with 30 days' notice to existing subscribers.

## 8. Acceptable Use

You agree not to:
- Use the Service for any unlawful purpose or to violate any third party's rights;
- Attempt to reverse-engineer, scrape, or extract data from the Service beyond normal use;
- Use the Service to generate harmful, abusive, or illegal content;
- Circumvent usage limits, security measures, or access controls;
- Use another person's account without permission.

## 9. Third-Party Services

The Service relies on third-party providers, including Google Firebase (authentication, database, hosting) and Google Gemini API (AI features). Your use of the Service is also subject to those providers' terms where applicable. We are not responsible for outages or issues caused by third-party providers.

## 10. Intellectual Property

The Service, including its design, code, and branding (excluding User Content and AI-generated output), is owned by Ayan Ahmed and protected by intellectual property laws. You may not copy, modify, or distribute it without permission.

## 11. Disclaimers

THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT GUARANTEE THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT AI-GENERATED CONTENT WILL BE ACCURATE.

## 12. Limitation of Liability

TO THE MAXIMUM EXTENT PERMITTED BY LAW, AYAN AHMED SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF DATA, ACADEMIC OUTCOMES, OR PROFITS, ARISING FROM YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY FOR ANY CLAIM SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS BEFORE THE CLAIM AROSE (OR USD 50 IF YOU HAVE NOT PAID US ANYTHING).

## 13. Termination

We may suspend or terminate your access to the Service at any time for violation of these Terms. You may stop using the Service and delete your account at any time.

## 14. Changes to These Terms

We may update these Terms from time to time. We will notify you of material changes (e.g., via email or an in-app notice). Continued use after changes take effect constitutes acceptance.

## 15. Governing Law

These Terms are governed by the laws of Pakistan, without regard to conflict-of-law principles. Disputes shall be resolved in the courts of Lahore, Pakistan.

## 16. Contact

Questions about these Terms? Contact us at ayaicrypcoin@gmail.com.
`;

export const PRIVACY_POLICY_TEXT = `# Privacy Policy

**Last updated: August 11, 2026**

Ayan Ahmed ("we," "us," "our"), based in Lahore, Pakistan, operates AI Study Buddy (the "Service"). This Privacy Policy explains what data we collect, how we use it, and your rights regarding it.

## 1. Information We Collect

**Account information:** When you sign up (via Firebase Authentication — email/password, Google sign-in, etc.), we collect your name, email address, and authentication identifiers.

**User content:** Notes, documents, images, and other files you upload or create — including content stored in your notebooks, flashcards, quizzes, resumes, and scholarship/university trackers.

**AI interaction data:** Prompts you send and responses generated through AI features (powered by Google's Gemini API), including chat messages, generated summaries, and study materials.

**Usage data:** Information about how you interact with the Service, such as feature usage, session activity, and device/browser information, which may be collected automatically (e.g., via Firebase Analytics, if enabled).

**Payment information:** If you subscribe to a paid tier, payment details are processed by our third-party payment processor — we do not store full card numbers ourselves.

## 2. How We Use Your Information

We use collected data to:
- Provide, operate, and maintain the Service;
- Generate AI-powered study content in response to your input;
- Authenticate your account and secure the Service;
- Improve and personalize your experience;
- Process payments for paid subscriptions;
- Communicate with you about updates, support, or policy changes;
- Comply with legal obligations.

## 3. How Your Data Is Shared

We share data with:
- **Google Firebase** — for authentication, database storage, and hosting;
- **Google Gemini API** — your prompts and relevant content are sent to Google's AI models to generate responses. Review [Google's API terms](https://ai.google.dev/gemini-api/terms) for how Google handles this data;
- **Payment processors** — if you subscribe to a paid plan;
- **Legal authorities** — if required by law, subpoena, or to protect our rights or user safety.

We do **not** sell your personal information to third parties.

## 4. Data Retention

We retain your account and content data for as long as your account is active. If you delete your account, we will delete or anonymize your personal data within 30 days, except where retention is required for legal, security, or dispute-resolution purposes.

## 5. Your Rights

Depending on your location, you may have the right to:
- Access, correct, or delete your personal data;
- Export your data;
- Object to or restrict certain processing;
- Withdraw consent where processing is based on consent.

To exercise these rights, contact us at ayaicrypcoin@gmail.com. If you have users in the EU, UK, or California, note that this policy covers general principles but does not include the full specific GDPR/CCPA disclosures those regions may legally require — get this reviewed by a lawyer before scaling there.

## 6. Children's Privacy

The Service is not directed at children under 13 (or the applicable minimum age in your region). We do not knowingly collect personal data from children under this age. If you believe a child has provided us data, contact us so we can remove it.

## 7. Data Security

We use industry-standard measures (including Firebase's built-in security features) to protect your data. However, no method of transmission or storage is 100% secure, and we cannot guarantee absolute security.

## 8. International Data Transfers

Your data may be processed in countries other than your own (e.g., on Google Cloud/Firebase infrastructure). By using the Service, you consent to this transfer.

## 9. Cookies & Tracking

We use essential cookies and local storage to keep you logged in and remember preferences (such as light/dark theme). If we add analytics or ad tracking in the future, this section will be updated, and a cookie consent banner will be added where legally required.

## 10. Changes to This Policy

We may update this Privacy Policy periodically. We'll notify you of material changes via email or an in-app notice. Continued use after changes take effect constitutes acceptance.

## 11. Contact Us

Questions about this Privacy Policy or your data? Contact us at ayaicrypcoin@gmail.com.
`;
