import React, { useState, useRef } from 'react';
import { 
  Brain, 
  Sparkles, 
  ZoomIn, 
  ZoomOut, 
  Maximize2, 
  BookOpen, 
  HelpCircle, 
  ArrowRight, 
  Layers, 
  X,
  Plus,
  Download,
  FileText,
  Image as ImageIcon,
  Check
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { MindMapData, MindMapNode } from '../types';

interface MindMapProps {
  data?: MindMapData;
  isLoading?: boolean;
  onGenerateMindMap: () => void;
  onAskAboutNode: (conceptLabel: string) => void;
}

export const MindMap: React.FC<MindMapProps> = ({
  data,
  isLoading,
  onGenerateMindMap,
  onAskAboutNode
}) => {
  const [zoomLevel, setZoomLevel] = useState(1);
  const [selectedNode, setSelectedNode] = useState<MindMapNode | null>(null);
  const [exportSuccess, setExportSuccess] = useState<string | null>(null);
  const svgRef = useRef<SVGSVGElement | null>(null);

  const handleExportMarkdown = () => {
    if (!data || !data.nodes) return;
    
    const topicTitle = data.topic || 'Document Concepts';
    let mdContent = `# Mind Map: ${topicTitle}\n\n`;
    mdContent += `> Generated by AI Study Buddy on ${new Date().toLocaleDateString()}\n\n`;
    mdContent += `## 🧠 Concept Nodes (${data.nodes.length})\n\n`;
    
    data.nodes.forEach((node, idx) => {
      mdContent += `${idx + 1}. **${node.label}** *(${node.category || 'Concept'})*\n`;
      if (node.description) {
        mdContent += `   - ${node.description}\n`;
      }
      mdContent += `\n`;
    });

    if (data.connections && data.connections.length > 0) {
      mdContent += `## 🔗 Concept Relationships (${data.connections.length})\n\n`;
      data.connections.forEach((conn) => {
        mdContent += `- **${conn.fromId}** --[ *${conn.relation || 'relates to'}* ]--> **${conn.toId}**\n`;
      });
      mdContent += `\n`;
    }

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `MindMap-${topicTitle.toLowerCase().replace(/[^a-z0-9]/g, '-')}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setExportSuccess('Markdown File Exported!');
    setTimeout(() => setExportSuccess(null), 3000);
  };

  const handleExportPNG = () => {
    if (!svgRef.current || !data) return;

    try {
      const svgElement = svgRef.current;
      const svgData = new XMLSerializer().serializeToString(svgElement);
      const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
      const blobURL = URL.createObjectURL(svgBlob);

      const image = new Image();
      image.onload = () => {
        const canvas = document.createElement('canvas');
        canvas.width = 1400;
        canvas.height = 1120;
        const context = canvas.getContext('2d');
        if (!context) return;

        // Dark canvas background styling
        context.fillStyle = '#020617'; // slate-950
        context.fillRect(0, 0, canvas.width, canvas.height);

        // Header watermark
        context.fillStyle = '#818cf8';
        context.font = 'bold 24px sans-serif';
        context.fillText(`AI Study Buddy Mind Map: ${data.topic || 'Concept Graph'}`, 40, 50);

        context.drawImage(image, 0, 0, 1400, 1120);

        const pngURL = canvas.toDataURL('image/png');
        const downloadLink = document.createElement('a');
        downloadLink.href = pngURL;
        downloadLink.download = `MindMap-${(data.topic || 'concept').toLowerCase().replace(/[^a-z0-9]/g, '-')}.png`;
        document.body.appendChild(downloadLink);
        downloadLink.click();
        document.body.removeChild(downloadLink);
        URL.revokeObjectURL(blobURL);

        setExportSuccess('High-Res PNG Image Exported!');
        setTimeout(() => setExportSuccess(null), 3000);
      };

      image.src = blobURL;
    } catch (err) {
      console.error('Failed to export PNG:', err);
    }
  };

  if (isLoading) {
    return (
      <div className="p-12 text-center bg-slate-900/60 border border-slate-800 rounded-[2.5rem] my-8 max-w-4xl mx-auto">
        <div className="w-16 h-16 bg-indigo-600/20 text-indigo-400 rounded-3xl flex items-center justify-center mx-auto mb-4 animate-bounce">
          <Brain className="w-8 h-8" />
        </div>
        <h3 className="text-xl font-black text-white">Synthesizing Interactive Mind Map...</h3>
        <p className="text-xs text-slate-400 mt-2 max-w-md mx-auto">
          Extracting key concept relationships, topic trees, and connection links from your active sources.
        </p>
      </div>
    );
  }

  if (!data || !data.nodes || data.nodes.length === 0) {
    return (
      <div className="p-12 text-center bg-slate-900/60 border border-slate-800 rounded-[2.5rem] my-8 max-w-4xl mx-auto">
        <div className="w-16 h-16 bg-indigo-600/10 text-indigo-400 rounded-3xl flex items-center justify-center mx-auto mb-4">
          <Brain className="w-8 h-8" />
        </div>
        <h3 className="text-xl font-black text-white">Interactive Concept Mind Map</h3>
        <p className="text-xs text-slate-400 mt-2 max-w-md mx-auto mb-6">
          Visualize your document topics as an interconnected visual graph. Click any concept node to explore its details or test yourself on it.
        </p>
        <button
          onClick={onGenerateMindMap}
          className="px-8 py-4 bg-indigo-600 hover:bg-indigo-500 text-white rounded-2xl font-black text-xs uppercase tracking-widest transition-all shadow-lg shadow-indigo-600/30 active:scale-95"
        >
          Generate Mind Map Now
        </button>
      </div>
    );
  }

  // Position nodes in a radial / grid pattern for SVG rendering
  const nodesCount = data.nodes.length;
  const radius = 220;
  const centerX = 350;
  const centerY = 280;

  const nodePositions = data.nodes.map((node, index) => {
    if (index === 0) {
      // Root central node
      return { ...node, x: centerX, y: centerY };
    }
    const angle = ((index - 1) / (nodesCount - 1)) * 2 * Math.PI;
    const x = centerX + radius * Math.cos(angle);
    const y = centerY + radius * Math.sin(angle);
    return { ...node, x, y };
  });

  return (
    <div className="space-y-6 max-w-6xl mx-auto pb-12">
      {/* Top Banner & Canvas Toolbar */}
      <div className="bg-slate-900/80 border border-slate-800 p-6 rounded-[2.5rem] flex flex-col md:flex-row items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-indigo-600/20 text-indigo-400 rounded-xl flex items-center justify-center">
            <Brain className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-lg font-black text-white">Document Concept Mind Map</h3>
            <p className="text-xs text-slate-400">{data.nodes.length} Key Concepts • {data.connections?.length || 0} Relationship Links</p>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {exportSuccess && (
            <span className="text-xs font-bold text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-3 py-1.5 rounded-xl flex items-center gap-1.5 animate-fadeIn">
              <Check className="w-3.5 h-3.5" />
              {exportSuccess}
            </span>
          )}

          <div className="flex items-center gap-1 bg-slate-950 p-1.5 rounded-2xl border border-slate-800">
            <button
              onClick={handleExportPNG}
              className="px-3 py-1.5 bg-indigo-600/20 hover:bg-indigo-600/40 border border-indigo-500/30 text-indigo-300 rounded-xl text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer"
              title="Export Mind Map as High-Res PNG Image"
            >
              <ImageIcon className="w-3.5 h-3.5" />
              <span>Export PNG</span>
            </button>

            <button
              onClick={handleExportMarkdown}
              className="px-3 py-1.5 bg-emerald-600/20 hover:bg-emerald-600/40 border border-emerald-500/30 text-emerald-300 rounded-xl text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer"
              title="Export Mind Map as Structured Markdown (.md)"
            >
              <FileText className="w-3.5 h-3.5" />
              <span>Export Markdown</span>
            </button>
          </div>

          <div className="flex items-center gap-1 bg-slate-950 p-1.5 rounded-2xl border border-slate-800">
            <button
              onClick={() => setZoomLevel(prev => Math.min(prev + 0.15, 1.6))}
              className="p-2 text-slate-400 hover:text-white hover:bg-slate-800 rounded-xl transition-all"
              title="Zoom In"
            >
              <ZoomIn className="w-4 h-4" />
            </button>
            <button
              onClick={() => setZoomLevel(prev => Math.max(prev - 0.15, 0.6))}
              className="p-2 text-slate-400 hover:text-white hover:bg-slate-800 rounded-xl transition-all"
              title="Zoom Out"
            >
              <ZoomOut className="w-4 h-4" />
            </button>
            <button
              onClick={() => setZoomLevel(1)}
              className="p-2 text-slate-400 hover:text-white hover:bg-slate-800 rounded-xl transition-all"
              title="Reset Scale"
            >
              <Maximize2 className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>

      {/* SVG Interactive Visual Canvas */}
      <div className="bg-slate-950 border border-slate-800 rounded-[2.5rem] p-4 md:p-8 min-h-[580px] overflow-auto flex items-center justify-center relative shadow-inner">
        <div 
          className="transition-transform duration-300 origin-center"
          style={{ transform: `scale(${zoomLevel})` }}
        >
          <svg ref={svgRef} width="700" height="560" className="overflow-visible">
            {/* Draw connection lines */}
            {data.connections?.map((conn, idx) => {
              const fromNode = nodePositions.find(n => n.id === conn.fromId || n.label.toLowerCase().includes(conn.fromId.toLowerCase()));
              const toNode = nodePositions.find(n => n.id === conn.toId || n.label.toLowerCase().includes(conn.toId.toLowerCase()));

              if (!fromNode || !toNode) return null;

              const midX = (fromNode.x + toNode.x) / 2;
              const midY = (fromNode.y + toNode.y) / 2;

              return (
                <g key={`conn-${conn.fromId}-${conn.toId}-${idx}`}>
                  <line
                    x1={fromNode.x}
                    y1={fromNode.y}
                    x2={toNode.x}
                    y2={toNode.y}
                    stroke="#4f46e5"
                    strokeWidth="2"
                    strokeDasharray="4 4"
                    opacity="0.6"
                  />
                  {conn.relation && (
                    <text
                      x={midX}
                      y={midY}
                      fill="#818cf8"
                      fontSize="9"
                      fontWeight="bold"
                      textAnchor="middle"
                      className="bg-slate-950 px-1 py-0.5"
                    >
                      {conn.relation}
                    </text>
                  )}
                </g>
              );
            })}

            {/* Draw Concept Nodes */}
            {nodePositions.map((node, idx) => {
              const isRoot = idx === 0;
              return (
                <g 
                  key={`node-${node.id || idx}-${idx}`} 
                  transform={`translate(${node.x}, ${node.y})`}
                  onClick={() => setSelectedNode(node)}
                  className="cursor-pointer group"
                >
                  <circle
                    r={isRoot ? "42" : "32"}
                    fill={isRoot ? "#4f46e5" : "#1e1b4b"}
                    stroke={isRoot ? "#818cf8" : "#6366f1"}
                    strokeWidth={isRoot ? "3" : "2"}
                    className="transition-transform group-hover:scale-110 shadow-xl"
                  />
                  <text
                    textAnchor="middle"
                    dy="4"
                    fill="#ffffff"
                    fontSize={isRoot ? "11" : "9"}
                    fontWeight="bold"
                    className="pointer-events-none select-none"
                  >
                    {node.label.length > 16 ? node.label.slice(0, 14) + '...' : node.label}
                  </text>
                </g>
              );
            })}
          </svg>
        </div>
      </div>

      {/* Concept Node Modal Detail */}
      <AnimatePresence>
        {selectedNode && (
          <div className="fixed inset-0 z-[120] bg-slate-950/80 backdrop-blur-md overflow-y-auto p-4 md:p-8 flex justify-center items-start">
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className="bg-slate-900 border border-slate-800 text-slate-100 w-full max-w-lg rounded-[2.5rem] shadow-2xl overflow-hidden my-auto p-6 md:p-8 relative space-y-4"
            >
              <div className="flex items-center justify-between border-b border-slate-800 pb-4">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-indigo-600/20 text-indigo-400 rounded-xl flex items-center justify-center">
                    <Brain className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="text-lg font-black text-white">{selectedNode.label}</h3>
                    <p className="text-xs text-indigo-400">{selectedNode.category || 'Core Concept'}</p>
                  </div>
                </div>
                <button
                  onClick={() => setSelectedNode(null)}
                  className="p-2 text-slate-400 hover:text-white bg-slate-800/50 rounded-xl"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>

              <div className="p-4 bg-slate-950 rounded-2xl border border-slate-800 text-xs text-slate-200 leading-relaxed font-medium">
                {selectedNode.description || 'Key topic synthesized from your active notebook material.'}
              </div>

              <div className="pt-2 flex flex-col gap-2">
                <button
                  onClick={() => {
                    const label = selectedNode.label;
                    setSelectedNode(null);
                    onAskAboutNode(label);
                  }}
                  className="w-full py-3.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-2xl font-bold text-xs uppercase tracking-wider flex items-center justify-center gap-2 transition-all shadow-lg"
                >
                  <Sparkles className="w-4 h-4" />
                  Ask Tutor About "{selectedNode.label}"
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};
export default MindMap;
